# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'mykiwi'

branding:
  icon: 'alert-octagon'
  color: 'orange'

name: 'Cleanup disabled workflows'
description: 'Automate the cleaning of your disabled workflows'

runs:
  using: "composite"
  steps:

    - uses: actions/github-script@v6
      with:
        script: |
          const githubContext = {
            owner: context.repo.owner,
            repo: context.repo.repo,
          }

          const workflows = await github.rest.actions
            .listRepoWorkflows(githubContext)
            .then(response => response.data.workflows.filter(workflow => workflow.state == 'disabled_manually'))

          console.log('::group::List of disabled workflows')
          console.log(workflows)
          console.log('::endgroup::')

          for (const workflow of workflows) {
            const {data: {workflow_runs}} = await github.rest.actions
              .listWorkflowRuns({
                ...githubContext,
                workflow_id: workflow.id,
              })

            console.log(`::group::Workflow #${workflow.id} >> Runs`)
            console.log(workflow_runs)
            console.log('::endgroup::')
            
            for (const workflow_run of workflow_runs) {
              const response = await github.rest.actions.deleteWorkflowRun({
                ...githubContext,
                run_id: workflow_run.id,
              })

              console.log(`::group::Workflow #${workflow.id} >> Run #${workflow_run.id} >> Delete`)
              console.log(response)
              console.log('::endgroup::')
            }
          }
